site :opscode

cookbook 'apt', '~> 2.2.1'
cookbook 'postgresql', '~> 3.1.0'
cookbook 'ruby_build', github: 'fnichol/chef-ruby_build', tag: 'v0.8.0'
cookbook 'rbenv', github: 'fnichol/chef-rbenv', tag: 'v0.7.2'
cookbook 'imagemagick'
