# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu-server-12042-x64-vbox4210-nocm"
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box"

  # uncomment this if you want to set the hostname of machine
  # config.vm.hostname = '<project_name>'
  
  # config.vm.provider "virtualbox" do |v|
  #   v.customize ["modifyvm", :id, "--memory", 1024]
  #   v.customize ["modifyvm", :id, "--cpus",   "2"  ]
  # end

  config.ssh.forward_agent = true

  config.vm.network :forwarded_port, guest: 3000, host: 3000 # rails s

  # uncomment this if you want to use NFS
  # config.vm.network :private_network, ip: '10.11.12.18'
  # config.vm.synced_folder "./<project_name>", "/<project_name>", nfs: true

  # plugins
  config.berkshelf.enabled = true
  config.omnibus.chef_version = :latest

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe 'apt'

    chef.add_recipe 'ruby_build'
    chef.add_recipe 'rbenv::user'

    chef.add_recipe 'postgresql::server'

    chef.add_recipe 'postgresql::client'
    chef.add_recipe 'imagemagick::devel'

    chef.json = {
      :postgresql => {
        :password => {
          :postgres => "password"
        },
        :pg_hba => [
          { :type => 'local', :db => 'all', :user => 'all', :addr => nil, :method => 'trust' },
          { :type => 'local', :db => 'all', :user => 'postgres', :addr => nil, :method => 'trust' },
          { :type => 'host', :db => 'all', :user => 'all', :addr => '127.0.0.1/32', :method => 'trust' }
        ]
      },
      :rbenv      => {
        :user_installs => [
          {
            :user   => "vagrant",
            :rubies => [
              "2.0.0-p247"
            ],
            :global => "2.0.0-p247",
            'gems'    => {
              '2.0.0-p247'    => [
              { 'name'    => 'bundler' }
            ]}
          }
        ]
      }
    }

  end
end
